"""Service for generating PDF reports from digest summaries."""

import logging
import re
from datetime import datetime
from io import BytesIO

from fpdf import FPDF

logger = logging.getLogger(__name__)

# Map Unicode characters that can't be encoded by Helvetica (latin-1) to ASCII equivalents
_UNICODE_MAP = str.maketrans({
    "\u2014": "-",   # em dash
    "\u2013": "-",   # en dash
    "\u2018": "'",   # left single quote
    "\u2019": "'",   # right single quote
    "\u201c": '"',   # left double quote
    "\u201d": '"',   # right double quote
    "\u2022": "*",   # bullet
    "\u2026": "...", # ellipsis
    "\u00b7": ".",   # middle dot
    "\u2122": "(TM)",
    "\u00ae": "(R)",
    "\u00a9": "(C)",
    "\u2019": "'",
    "\u00a0": " ",   # non-breaking space
})


def _s(text: str) -> str:
    """Sanitize text to latin-1 safe characters."""
    text = text.translate(_UNICODE_MAP)
    # Replace any remaining non-latin-1 characters with "?"
    return text.encode("latin-1", errors="replace").decode("latin-1")


class DigestPDF(FPDF):
    """Custom FPDF subclass with header and footer."""

    def __init__(self, digest_name: str, run_date: str):
        super().__init__()
        self.digest_name = _s(digest_name)
        self.run_date = _s(run_date)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(80, 80, 80)
        self.cell(0, 8, self.digest_name, align="L")
        self.set_font("Helvetica", "", 10)
        self.cell(0, 8, self.run_date, align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f"Page {self.page_no()} - Generated by Email Digest Summarizer", align="C")


class PdfService:
    """Service for generating PDF digests."""

    def generate(self, detailed_text: str, digest_name: str, images: list = None) -> bytes:
        """
        Generate a PDF from the plain-text detailed summary.

        Args:
            detailed_text: Structured plain text from the LLM detailed section
            digest_name: Name of the digest (used in header/title)

        Returns:
            PDF as bytes
        """
        try:
            run_date = datetime.now().strftime("%d %B %Y, %H:%M SGT")
            pdf = DigestPDF(digest_name=digest_name, run_date=run_date)
            pdf.set_auto_page_break(auto=True, margin=15)
            pdf.add_page()

            # Title
            pdf.set_font("Helvetica", "B", 16)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(0, 10, _s(digest_name), align="C", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 6, _s(run_date), align="C", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(6)
            pdf.set_draw_color(60, 100, 180)
            pdf.set_line_width(0.5)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(6)

            self._render_body(pdf, detailed_text)

            if images:
                self._render_images(pdf, images)

            buf = BytesIO()
            pdf.output(buf)
            logger.info(f"PDF generated successfully ({buf.tell()} bytes)")
            return buf.getvalue()

        except Exception as e:
            logger.error(f"Error generating PDF: {e}")
            raise

    def _render_body(self, pdf: DigestPDF, text: str) -> None:
        """Parse the structured plain-text and render sections into the PDF."""
        lines = text.splitlines()

        for line in lines:
            stripped = line.rstrip()
            if not stripped:
                pdf.ln(2)
                continue

            indent = len(line) - len(line.lstrip())
            safe = _s(stripped)

            # Category heading: no indent, one of the four known categories
            _CATEGORIES = {"Macro", "FX", "Bonds", "Others"}
            if indent == 0 and not stripped.startswith("-") and not stripped.startswith("Source:"):
                pdf.ln(4)
                pdf.set_font("Helvetica", "B", 13)
                pdf.set_text_color(30, 70, 160)
                pdf.set_fill_color(235, 242, 255)
                pdf.cell(0, 8, safe, fill=True, new_x="LMARGIN", new_y="NEXT")
                pdf.ln(1)

            # Product type: 2-space indent
            elif indent == 2 and not stripped.startswith("-") and not stripped.startswith("Source:"):
                pdf.ln(2)
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(50, 50, 50)
                pdf.cell(0, 7, safe, new_x="LMARGIN", new_y="NEXT")

            # Instrument line: starts with "- "
            elif stripped.startswith("- "):
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(20, 20, 20)
                content = _s(stripped[2:])
                pdf.set_x(14)
                pdf.multi_cell(0, 6, f"*  {content}")

            # Source line
            elif stripped.startswith("Source:"):
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(120, 120, 120)
                pdf.set_x(18)
                pdf.multi_cell(0, 5, safe)
                pdf.ln(1)

            # Body text
            else:
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(50, 50, 50)
                pdf.set_x(18)
                pdf.multi_cell(0, 6, safe)

    def _render_images(self, pdf: DigestPDF, images: list) -> None:
        """Add a Charts & Figures section to the PDF with all extracted images."""
        import tempfile
        import os
        from PIL import Image as PilImage

        # Section heading
        pdf.add_page()
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 70, 160)
        pdf.set_fill_color(235, 242, 255)
        pdf.cell(0, 8, "Charts & Figures", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        MAX_WIDTH = 180   # mm — fits within A4 margins
        MAX_HEIGHT = 120  # mm — keep charts a reasonable height

        tmp_files = []
        try:
            for img_data in images:
                try:
                    # Use Pillow to validate, convert to RGB JPEG, and get dimensions
                    pil_img = PilImage.open(BytesIO(img_data["data"]))
                    if pil_img.mode not in ("RGB", "L"):
                        pil_img = pil_img.convert("RGB")

                    # Scale to fit MAX_WIDTH × MAX_HEIGHT preserving aspect ratio
                    w_px, h_px = pil_img.size
                    dpi = 96
                    w_mm = w_px * 25.4 / dpi
                    h_mm = h_px * 25.4 / dpi
                    scale = min(MAX_WIDTH / w_mm, MAX_HEIGHT / h_mm, 1.0)
                    w_mm *= scale
                    h_mm *= scale

                    # Write to a temp JPEG file (fpdf2 needs a file path or BytesIO)
                    tmp = tempfile.NamedTemporaryFile(suffix=".jpg", delete=False)
                    pil_img.save(tmp, format="JPEG", quality=85)
                    tmp.close()
                    tmp_files.append(tmp.name)

                    # Check if image fits on current page, else new page
                    if pdf.get_y() + h_mm + 12 > pdf.h - pdf.b_margin:
                        pdf.add_page()

                    pdf.image(tmp.name, x=10, w=w_mm, h=h_mm)
                    pdf.ln(2)

                    # Caption
                    caption = _s(img_data.get("filename", "Chart"))
                    pdf.set_font("Helvetica", "I", 8)
                    pdf.set_text_color(120, 120, 120)
                    pdf.cell(0, 5, caption, new_x="LMARGIN", new_y="NEXT")
                    pdf.ln(4)

                except Exception as e:
                    logger.error(f"Failed to render image {img_data.get('filename')}: {e}")
                    continue
        finally:
            for path in tmp_files:
                try:
                    os.unlink(path)
                except Exception:
                    pass
